### ISSUE TITLE
entities/id_lookup.json not returning id for bioguid

### ISSUE THREAD

**Issue by jimbol** [sunlightlabs/datacommons#18]
Hitting http://transparencydata.com/api/1.0/entities/id_lookup.json with a `bioguide_id` of `B001293` returns an empty array.  Should return `entity_id` for Rep. Mike Bishop.

**Comment by boblannon** [comment]
Pushing an update today that should take care of this and other cases involving new MoC.  I'll let you know when it's live.

**Comment by boblannon** [comment]
This should be fixed with the latest update.  Thanks for your feedback!

**Comment by jimbol** [comment]
Thanks for getting to this so quickly!
